# docker stack deploy -c ./timescale-stack.yml homeward_timescale
version: "3.4"
services:
  tele_api:
    image: "lionants02/vidu_api_demo:a8"
    restart: always
    ports:
      - "12384:8080"
    volumes:
      - "./db.properties:/nstda/tele_api/hikarisimple.properties:ro"
    env_file: ./.env
    healthcheck:
      test: [ "CMD", "curl","--fail" ,"http://127.0.0.1:8080" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '4'
          memory: 2100M